name: 'My superb action'
description: 'An action that does superb things'
author: 'MMM Corp'

# Define your inputs here.
inputs:
  who-to-greet:
    description: 'Greetings'
    required: true
    default: 'Maxime'

# Define your outputs here.
outputs:
  greeting:
    description: 'Just the output'

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
